// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizTwo.Models;

#nullable disable

namespace QuizTwo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizTwo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "a",
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "b",
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Description = "c",
                            Name = "Hatchback"
                        });
                });

            modelBuilder.Entity("QuizTwo.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProfileId")
                        .IsUnique();

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerProfileId = 1,
                            DriverLicenseNumber = "D1234567",
                            Email = "ahmed@gamil.com",
                            Name = "Ahmed Hassan",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            CustomerProfileId = 2,
                            DriverLicenseNumber = "D7654321",
                            Email = "ali@gmail.com",
                            Name = "Ali Ahmed",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            CustomerProfileId = 3,
                            DriverLicenseNumber = "D1122334",
                            Email = "sara@gmail.com",
                            Name = "Sara Ali",
                            PhoneNumber = "1122334455"
                        });
                });

            modelBuilder.Entity("QuizTwo.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CustomerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "New York",
                            DateOfBirth = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2219),
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            City = "Los Angeles",
                            DateOfBirth = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2329),
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            City = "Chicago",
                            DateOfBirth = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2333),
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Pine St",
                            City = "Houston",
                            DateOfBirth = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2337),
                            Nationality = "Egyptian"
                        });
                });

            modelBuilder.Entity("QuizTwo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jogn@mai.com",
                            FullName = "John Doe",
                            HireDate = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2477),
                            PhoneNumber = "555-1234",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = 2,
                            Email = "horg@gmail.com",
                            FullName = "Jane Smith",
                            HireDate = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2488),
                            PhoneNumber = "555-5678",
                            Position = "Sales Associate"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mich@gmail.om",
                            FullName = "Michael Johnson",
                            HireDate = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2493),
                            PhoneNumber = "555-9012",
                            Position = "Sales Representative"
                        });
                });

            modelBuilder.Entity("QuizTwo.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            EmployeeId = 1,
                            PaymentMethod = "Visa",
                            SalePrice = 24000m,
                            SalesDate = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2544)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            EmployeeId = 2,
                            PaymentMethod = "Visa",
                            SalePrice = 19000m,
                            SalesDate = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2550)
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            EmployeeId = 3,
                            PaymentMethod = "Visa",
                            SalePrice = 17000m,
                            SalesDate = new DateTime(2026, 10, 1, 14, 17, 23, 805, DateTimeKind.Local).AddTicks(2555)
                        });
                });

            modelBuilder.Entity("QuizTwo.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "blue",
                            FuelType = "petrol",
                            Make = "Toyota",
                            Mileage = 0,
                            Model = "Camry",
                            Price = 25000m,
                            SaleId = 1,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "1Hfosdjf",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "blue",
                            FuelType = "petrol",
                            Make = "Honda",
                            Mileage = 0,
                            Model = "Civic",
                            Price = 20000m,
                            SaleId = 2,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "2Hfosdjf",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "blue",
                            FuelType = "petrol",
                            Make = "Ford",
                            Mileage = 0,
                            Model = "Focus",
                            Price = 18000m,
                            SaleId = 3,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "3Hfosdjf",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("QuizTwo.Models.Customer", b =>
                {
                    b.HasOne("QuizTwo.Models.CustomerProfile", "CustomerProfile")
                        .WithOne("Customer")
                        .HasForeignKey("QuizTwo.Models.Customer", "CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("QuizTwo.Models.Sale", b =>
                {
                    b.HasOne("QuizTwo.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizTwo.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QuizTwo.Models.Vehicle", b =>
                {
                    b.HasOne("QuizTwo.Models.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizTwo.Models.Sale", "Sale")
                        .WithOne("Vehicle")
                        .HasForeignKey("QuizTwo.Models.Vehicle", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("QuizTwo.Models.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("QuizTwo.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("QuizTwo.Models.CustomerProfile", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("QuizTwo.Models.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("QuizTwo.Models.Sale", b =>
                {
                    b.Navigation("Vehicle")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
